services:

  Polidog\HypermediaBundle\EmbedRequestExecutor:
      arguments:
          $kernel: '@http_kernel'

  Polidog\HypermediaBundle\UrlGenerator:
      arguments:
          $router: '@router'
          $enableFullPath: '%hypermedia.enable_absolute_url%'

  # Subscriber
  Polidog\HypermediaBundle\EventListener\ViewListenerSubscriber:
      arguments:
          $embedRequestExecutor: '@Polidog\HypermediaBundle\EmbedRequestExecutor'
          $urlGenerator: '@Polidog\HypermediaBundle\UrlGenerator'
      tags:
          - { name: kernel.event_subscriber }

  Polidog\HypermediaBundle\EventListener\AnnotationSubscriber:
      arguments:
          $annotationReader: '@annotation_reader'
          $halContentType: '%hypermedia.hal_content_type%'
      tags:
          - { name: kernel.event_subscriber }
